import { AsciiDataTypeValue } from "../class/ascii";
import { BigIntDataTypeValue } from "../class/bigint";
import { BlobDataTypeValue } from "../class/blob";
import { BooleanDataTypeValue } from "../class/boolean";
import { DateDataTypeValue } from "../class/date";
import { DecimalDataTypeValue } from "../class/decimal";
import { DoubleDataTypeValue } from "../class/double";
import { InetDataTypeValue } from "../class/inet";
import { IntDataTypeValue } from "../class/int";
import { ListDataTypeValue } from "../class/list";
import { MapDataTypeValue } from "../class/map";
import { SetDataTypeValue } from "../class/set";
import { TextDataTypeValue } from "../class/text";
import { TimeDataTypeValue } from "../class/time";
import { TimestampDataTypeValue } from "../class/timestamp";
import { TimeUuidDataTypeValue } from "../class/timeuuid";
import { TupleDataTypeValue } from "../class/tuple";
import { UuidDataTypeValue } from "../class/uuid";

export interface DataTypeClass {
    ascii: AsciiDataTypeValue;
    bigint: BigIntDataTypeValue;
    blob: BlobDataTypeValue;
    boolean: BooleanDataTypeValue;
    counter: IntDataTypeValue;
    date: DateDataTypeValue;
    decimal: DecimalDataTypeValue;
    double: DoubleDataTypeValue;
    float: DoubleDataTypeValue;
    frozen: any;
    inet: InetDataTypeValue;
    int: IntDataTypeValue;
    list: ListDataTypeValue;
    map: MapDataTypeValue;
    set: SetDataTypeValue;
    smallint: IntDataTypeValue;
    text: TextDataTypeValue;
    time: TimeDataTypeValue;
    timestamp: TimestampDataTypeValue;
    timeuuid: TimeUuidDataTypeValue;
    tinyint: IntDataTypeValue;
    tuple: TupleDataTypeValue;
    uuid: UuidDataTypeValue;
    varchar: TextDataTypeValue;
    varint: IntDataTypeValue;
}
